// Extracts a few CJK glyphs from Noto Serif SC (SIL OFL) as vector outlines
// for templates, so the app doesn't need to ship a multi-megabyte CJK font.
// Usage: npm install --no-save @fontsource/noto-serif-sc && node scripts/extract-glyphs.js
const fs = require('fs');
const path = require('path');
const ot = require('opentype.js');

const file = path.join(__dirname, '..', 'node_modules/@fontsource/noto-serif-sc/files/noto-serif-sc-chinese-simplified-700-normal.woff');
const buf = fs.readFileSync(file);
const font = ot.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const r = (n) => Math.round(n * 10) / 10;
const out = {};
for (const text of ['金龙']) {
  // lay out at 100 units per em; y down
  const p = font.getPath(text, 0, 88, 100);
  out[text] = p.commands.map((c) => {
    const o = { type: c.type };
    for (const k of ['x1', 'y1', 'x2', 'y2', 'x', 'y']) if (k in c) o[k] = r(c[k]);
    return o;
  });
}
const js = `// Generated by scripts/extract-glyphs.js from Noto Serif SC Bold (SIL Open Font License 1.1).
// Glyph outlines in font units (100 per em), y pointing down.
export const GLYPHS = ${JSON.stringify(out)};
`;
fs.writeFileSync(path.join(__dirname, '..', 'src/js/glyphs.js'), js);
fs.copyFileSync(path.join(__dirname, '..', 'node_modules/@fontsource/noto-serif-sc/LICENSE'), path.join(__dirname, '..', 'src/vendor/fonts/noto-serif-sc.LICENSE.txt'));
console.log('wrote', Object.keys(out), js.length, 'bytes');
